Move check version scripts into one workflow

diff --git a/.github/workflows/check-versions.yaml b/.github/workflows/check-versions.yaml
--- a/.github/workflows/check-versions.yaml
+++ b/.github/workflows/check-versions.yaml
@@ -1,4 +1,4 @@
-name: TS Plugin Workers Version Check
+name: Check NPM Versions
 
 on:
   pull_request:
@@ -9,10 +9,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  version-check:
+  plugin-version-check:
     runs-on: ubuntu-latest
-    permissions:
-      pull-requests: write
     steps:
       - uses: actions/checkout@v2
 
@@ -56,24 +54,44 @@ jobs:
             exit 1
           fi
 
-      - name: Add comment if version is not bumped
-        if: failure()
+  wasm-version-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Check for "skip-version-bump" label
+        id: check_label
         shell: bash
         run: |
-          MESSAGE="Error: The version in package.json has not been bumped."
-          echo $MESSAGE
-          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV
+          SKIP_VERSION_BUMP=${{contains(github.event.pull_request.labels.*.name, 'skip-version-check') }}
+          if $SKIP_VERSION_BUMP; then
+            echo "Skip version bump label found. Exiting."
+          else
+            exit 1
+          fi
+        continue-on-error: true
 
-      - name: Post comment
-        if: failure()
-        uses: actions/github-script@v5
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          script: |
-            const message = process.env.MESSAGE;
-            github.rest.issues.createComment({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-              body: message
-            });
+      - name: Get base branch version
+        shell: bash
+        run: |
+          git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
+          echo "BASE_VERSION=$(git show origin/${{ github.base_ref }}:package.json | node -p "require('./package.json').version")" >> $GITHUB_ENV
+
+      - name: Get PR branch version
+        shell: bash
+        run: |
+          echo "PR_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
+
+      - name: Check if version is bumped
+        id: check_bump
+        shell: bash
+        run: |
+          echo "Comparing base version $BASE_VERSION to the current version $PR_VERSION."
+          COMPARABLE_BASE_VERSION=$($GITHUB_WORKSPACE/scripts/ci/parse_version.sh $BASE_VERSION)
+          COMPARABLE_PR_VERSION=$($GITHUB_WORKSPACE/scripts/ci/parse_version.sh $PR_VERSION)
+          if $COMPARABLE_BASE_VERSION -lt $COMPARABLE_PR_VERSION; then
+            echo "Version bumped in package.json."
+          else
+            echo "Error: The version in wasm/package.json has not been bumped."
+            exit 1
+          fi
